plugin:
    name: 'acte.matomophptracker::lang.plugin.name'
    description: 'acte.matomophptracker::lang.plugin.description'
    author: 'ACTE Solutions'
    icon: oc-icon-line-chart
    homepage: 'https://github.com/AdrienAdB/matomophptracker-plugin'
permissions:
    acte.matomophptracker.manage_settings:
        tab: 'acte.matomophptracker::lang.plugin.name'
        label: 'acte.matomophptracker::lang.plugin.name'
